taxonomy_stage_simple_detail = case_when(source=="Non-food" ~ "Non-food",
                                         !is.na(taxon) ~ taxon,
                                         is.na(taxon) & !is.na(order) ~ paste0("UnID ", order),
                                         is.na(taxon) & is.na(order) & !is.na(class) ~ paste0("UnID", class),
                                         is.na(taxon) & is.na(order) & is.na(class) & !is.na(phylum) ~ paste0("UnID", phylum),
                                         
                                         TRUE ~ "FLAG"))



taxon_clean=="Acari" & stage=="L" ~ "Acari (larvae)",
taxon_clean=="Diptera" & source=="Benthic" ~ "Diptera (larvae/pupae)",
order=="Balanomorpha" ~ "Balanomorpha",

taxon_clean=="Isopoda" ~ "UnID Isopod",
taxon_clean=="Ostracoda" ~ "Ostracod",
taxon_clean=="Copepoda" ~ "Copepod (Harpacticoid)",
taxon_clean=="Phyllodocida" ~ "Phyllodocida",
taxon_clean=="Actinopterygii" ~ "Fish (unknown)",
taxon_clean=="Perciformes" ~ "Fish (likely sandlance)",
taxon_clean=="Teleostei" & !grepl("Perciformes", diet_comments) ~ "Fish (likely herring/sardine/anchovy)",
taxon_clean=="Teleostei" & grepl("Perciformes", diet_comments) ~ "Fish (likely sandlance)",
taxon_clean%in%c("Nematoda", "Trematoda") ~ "Internal parasite",
taxon_clean=="Amphipoda" ~ "Amphipod (adult/juvenile)",
taxon_clean%in%c("Crustacea", "Crustacean remains") ~ "UnID crustacean",
taxon_clean=="Decapoda" | order=="Decapoda" ~ "Decapod (zoae/megalopa)",
order=="Cumacea" ~ "Cumacea",
taxon_clean=="Insecta" & stage%in%c("A", "A/parts") ~ "UnID Insect (adult)",
taxon_clean=="Insecta" & stage%in%c("L", "P", "N", "N, P", "P, N", "P, L") ~ "UnID Insect (larvae/pupae/nymph)",
taxon_clean=="Insecta" & stage%notin%c("L", "P", "N", "N, P", "P, N", "P, L", "A", "A/parts") ~ "UnID Insect",
#source=="Planktonic" & taxon_clean=="Ostracoda" ~ "Ostracod",
source=="Terrestrial" ~ paste0(taxon_clean, " (adult)"),
#source=="Undetermined" & taxon_clean=="Amphipoda" ~ "Amphipod (adult/juvenile)",
source=="Undetermined" & taxon_clean=="Annelid" ~ "Annelid (unk)",
source=="Undetermined" & taxon_clean=="Diptera" ~ "Diptera (unk)",
#source=="Undetermined" & taxon_clean=="Crustacean remains" ~ "UnID crustacean",
#source=="Undetermined" & taxon_clean=="Decapoda" ~ "Decapod (zoae/megalopa)",
#source=="Undetermined" & taxon_clean=="Diptera" ~ "Diptera (larvae/pupae)",
#source=="Undetermined" & taxon_clean=="Insecta" ~ "UnID insect",
source=="Undetermined" & taxon_clean=="Invertebrate remains" ~ "UnID invert",
source=="Undetermined" & taxon_clean=="Lepidoptera" ~ "Lepidoptera (larvae)",
taxon_clean %in% c("Digested matter", "UnID remains") ~ "Unknown",
grepl("empty", diet_comments, ignore.case=T) ~ "Empty",
grepl("empty", taxon_clean, ignore.case=T) ~ "Empty",
TRUE ~ taxon_clean))